name: Vittjärvs VVO
description: Älgjakt i Vittjärv
meta_description: "Älgjakt i vittjärv"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: ""
domain_name: ""
google_analytics: "UA-18998977-1"
plugins: [jekyll-paginate]
permalink: /:categories/:year/:month/:title:output_ext

# Details for the RSS feed generator
url: ""
author: "vvo"

# Disqus config
disqus-shortname: ""
